development:
  adapter: postgresql
  encoding: unicode
  database: delish_development
  pool: 5
  username: ndonias
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: delish_test
  pool: 5
  username: ndonias
  password: